### PR TITLE
Allow claims annotations to be set in values file

### PR DESCRIPTION
**Pull request by john873950**
See https://github.com/microcks/microcks/issues/507

### CODE REVIEW

**Comment by lbroudoux** [comment]
Thanks a lot for this contribution, it's awesome!

I've got 2 questions:
* Shouldn't the `helm.sh/resource-policy` be defined as default? What is the best practice?
* Could you please re-target this PR to the `1.5.x` branch? This is where current dev are going.

**Review by lbroudoux — APPROVED** [review]
Great! Thanks.

**Comment by john873950** [comment]
Regarding defining a default, I tried to make the out-of-the-box behaviour the same as before so as to not confuse other users. The default behaviour is that when running helm uninstall it will delete the pvc (including all your keycloak configuration). I think that should be the default (otherwise you get stuff left lying around when you've uninstalled). There's an argument that it's annoying losing your keycloak config but then you can override the resource policy to fix that.

But it's up to you :)

**Comment by lbroudoux** [comment]
Agreed!

**Pull request merged**
