### PR TITLE
feat: add configuration for Cors origin

### PR DESCRIPTION
**Pull request by apoorva256**
### Description
Add Origin Configuration for REST mocks
- ...
- ...
- ...

### Related issue(s)
Ref: #956

### CODE REVIEW

**Comment by lbroudoux** [comment]
Awesome! Thanks! I'm having few days off and I'll be back next week to merge it. Thanks again  🙌

**Comment by apoorva256** [comment]
Can you give me access to the sonar so that i can reduce the number of code smells?

**Comment by lbroudoux** [comment]
Access to the reports and details should public. Do you face any issue ti access?

**Comment by apoorva256** [comment]
I found it. My bad i didn't i know you had to click on the status badge.

**Pull request merged**
