### PR TITLE
Renovation helm chart

### PR DESCRIPTION
**Pull request by Eroyi**
### Description

- [x] Separate async, postman and microcks from the original omni deployment yaml file.
- [x] Trim down and split the `service.yaml` file for each component.
- [x] Replace MongoDB with the latest Bitnami Chart.
- [x] Replace Keycloak(PostgreSQL) with the latest Bitnami Chart to solve the permission issue.
- [x] Replace Kafka(Zookeeper) with the latest Bitnami Chart, using KRaft to get rid of the Zookeeper.
- [x] Import `microcks-realms.json` in configMap with Bitnami Keycloak Chart. [Here](https://github.com/Eroyi/microcks/blob/master/install/kubernetes/microcks/templates/keycloak-realms.yaml)
- [x] Allowed users to customise the password for `user`, `manager` and `admin` accounts.  [Here](https://github.com/Eroyi/microcks/blob/master/install/kubernetes/microcks/values.yaml#L105)
- [x] Fixed the annotations section to adapt the AWS Network CSI. [Here](https://github.com/Eroyi/microcks/blob/master/install/kubernetes/microcks/charts/microcks/templates/microcks-svc.yaml)
- [x] Fixed microcks uri not having a port number attached when passed into the `microcks-realms.json` file to be used as `redirectUris` [Here](https://github.com/Eroyi/microcks/blob/master/install/kubernetes/microcks/templates/keycloak-realms.yaml#L166)
- [x] Provided an entry in `Values.yaml` to custom the HTTP protocol, allowing microcks using `http://` to connect with keycloak and http prefix in `redirectUris`. [Here](https://github.com/Eroyi/microcks/blob/master/install/kubernetes/microcks/templates/keycloak-realms.yaml#L165)
- [ ] Re-organised the `Values.yaml` for better integration *(90%)*
- [x] Optimise the `_helper.tpl`
- [ ] introduce more `_helper.tpl` to merge scattered configurations *(Kafka, Keycloak)*
- [ ] Regression test for all the integration and changes (Fixes mentioned above have been tested in our environment).
### Related issue(s)
Ref #1197 

### 🚫 DO NOT MERGE UNTIL THIS FLAG IS REMOVED.

### CODE REVIEW

**Comment by lbroudoux** [comment]
Awesome! Can you fix the DCO check by signing the commits please? This is a prequisites for CNCF projects.
I'll also change the destination branch as we're using the `1.10.x` branch  for developments

**Comment by lbroudoux** [comment]
Changing the base to `1.10.x` raises a bunch of conflicts..

**Comment by Eroyi** [comment]
> Changing the base to `1.10.x` raises a bunch of conflicts..

sure I'll take a look! I'll let you know as soon as I have an update.

**Comment by Eroyi** [comment]
- [ ] Clean up the deployment and config file for async
- [x] introducing schema-registry
- [ ] fix the wrong reference for an image in `_helpers.tpl` in microcks、postman and async
- [ ] fi the wrong components URL reference in microcks、postman and async
- [x] introducing _kafka.tpl to solve the messy Kafka URL reference issue
- [ ] introducing _mongodb.tpl to solve the messy MongoDB URL and authentication reference issue
- [ ] introducing _keycloak.tpl to solve the keycloak URL reference issue
- [ ] Realms.json need to be verified for bitnami/keycloak
- [ ] `configmap.yaml` for async needs to be verified that values can be rendered properly
- [ ] confirming schema-registry can be installed and work with async.

**Comment by lbroudoux** [comment]
Hey @Eroyi 
Do you have any ETA for this? I'm eager to test this out.
Also, can you fix the DCO check by signing the commits please? 
Thanks,

**Comment by Eroyi** [comment]
> Hey @Eroyi Do you have any ETA for this? I'm eager to test this out. Also, can you fix the DCO check by signing the commits please? Thanks,

Sorry, there is no ETA so far, It will probably be next week, it has been quite a busy week on my end.

The only thing that left is a regression test for the whole chart to make sure everything works fine.

For the DCO check, I think I fuckup up something. I'll remove my repo and fork again to fix the signoff error without rebasing the code after I verify my chart.

**Comment by lbroudoux** [comment]
Hey @Eroyi! I'm back from vacation and have some free cycles this week to work on this. Would you be able to re-init a new PR to start work from? Even if everything is not yet finished, it could be a great accelerator. I'd really love to embed this for `1.10.0` release...

**Comment by Eroyi** [comment]
> Hey @Eroyi! I'm back from vacation and have some free cycles this week to work on this. Would you be able to re-init a new PR to start work from? Even if everything is not yet finished, it could be a great accelerator. I'd really love to embed this for `1.10.0` release...

I figured I had made things too complex for me to handle alone. Reassembling those highly coupled configs in microcks with templates is quite painful, not to mention inserting them into a more complex chart maintained by a team in Bitami.

Yet I am making progress on constructing bare charts for microcks, postman and Kafka. And I successfully composed a chart for chaoss/grimoirelab from scratch, I think I might have found some tricks on it. Now I'm back to work on microcks. and once I get passed on `--dry-run`, I'll open another pr.

**Pull request closed without merging**
