### PR TITLE
$ref component not being parsed in json schema causing issue with nullable field

### LINKED ISSUE #995: $ref component not being parsed in json schema causing issue with nullable field
### Describe the bug

Hi, first of all thanks for all this awesome work with Microcks.
While trying to test an OpenAPI contract using Microcks the test were always failing, after further investigation I saw while debbuging microcks in local that $ref component are never parsed, causing field like "nullable: true" to be parsed as it is in the json schema resulting in error messages from the json schema validator saying that nullable is a unknown field and it'll be ignored.

examples:
```yaml
myProperty:
  type: string
  nullable: true
```
is resolved as
```json
{
  "myProperty": {
    "type" : "string",
    "nullable": true
  }
}
```
instead of
```json
{
  "myProperty": {
    "type" : ["string", "null"]
  }
}
```
This causing another issue when the json schema is used to validate the response, fields that are displayed as null are causing a validation issue because the schema want them to be the defined type in the OpenAPI spec causing an error message and making the test fail. 

### Expected behavior

Having OpenAPI properties resolving from
```yaml
myProperty:
  type: string
  nullable: true
```
to 
```json
{
  "myProperty": {
    "type" : ["string", "null"]
  }
}
```

### Actual behavior

OpenAPI properties resolving from
```yaml
myProperty:
  type: string
  nullable: true
```
to 
```json
{
  "myProperty": {
    "type" : "string",
    "nullable": true
  }
}
```

### How to Reproduce?

Create an OpenAPI specs that have arrays that use $ref as items

as the following

```yaml
openapi: 3.0.3
info:
  title: Sample API
  version: '1.0'
paths:
  /queen/members:
    get:
      parameters:
        - $ref: "#/components/parameters/alive"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/human"
              examples:
                "Alive":
                  $ref: '#/components/examples/alive'
                "Dead":
                  $ref: '#/components/examples/dead'

components:
  parameters:
    alive:
      name: isAlive
      in: path
      required: true
      schema:
        type: boolean
      examples:
        "Alive":
          value: true
        "Dead":
          value: false
  schemas:
    human:
      properties:
        name:
          type: string
          nullable: false
        birthDate:
          type: string
          format: date-time
          nullable: false
        deathDate:
          type: string
          format: date-time
          nullable: true

  examples:
    alive:
      value:
        - name: "Brian May"
          birthDate: "1947-07-19T00:00:00.0Z"
        - name: "Roger Taylor"
          birthDate: "1949-07-26T00:00:00.0Z"
        - name: "John Deacon"
          birthDate: "1951-08-19T00:00:00.0Z"
    dead:
      value:
        - name: "Freddy Mercury"
          birthDate: "1946-09-15T00:00:00.0Z"
          deathDate: "1946-11-24T00:00:00.0Z"
```` 

If your backend that implement this API is returning null field in the JSON response, the test will crash because null is not of type string

### Microcks version or git rev

1.8.x

### Install method (`docker-compose`, `helm chart`, `operator`, `docker-desktop extension`,...)

test-container, local docker setup

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by Snorkell**
### Description
- Added a step to parse the $ref component as well as the models
- Added a test to make sure that component having a nullable field won't make the json schema validator chash the api test
### Related issue(s)
Fixes #995

### CODE REVIEW

**Comment by lbroudoux** [comment]
Thanks again for this one! Before I start reviewing it, can you please sign the commit? This is a pre-requisite now that we're part of the CNCF.

Also as a note: the current branch where development is happening is `1.8.x`. It shouldn't change anything for this one but good to know for others ;-)

**Comment by Snorkell** [comment]
I had an error in my test, the returning dto were missing a null value and the open api spec vas missing a filed type: object, I fixed it

**Comment by lbroudoux** [comment]
Sorry to bother you with that, but it looks like the latest commit on test is not signed... Can you apply the signing please?
Thanks again!

**Comment by Snorkell** [comment]
Yeah sure my bad, I thought I had enable the automatic signoff, but apparently I didn't

**Review by lbroudoux — APPROVED** [review]
LGTM. Thanks a lot!

**Comment by lbroudoux** [comment]
Now merged 🎉  
Thanks a lot for your contribution!

**Pull request merged**
