### PR TITLE
Add missing headers for DynamicCorsFilter

### PR DESCRIPTION
**Pull request by Apoorva64**
### Description
When doing CORS request, we can send a header("Access-Control-Request-Headers") to request specific headers.
This PR implements this additional generation in the DynamicCorsFilder

### Related issue(s)
#

### CODE REVIEW

**Comment by lbroudoux** [comment]
Hi @Apoorva64 
Can you point to some reference documentation that explains this behavior? I am no Cors expert and was not aware of this mechanism... Could you share some reference link so that I'll understand if this behavior is standard? Thanks,

**Comment by Apoorva64** [comment]
CORS requests are explained here: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

The specifics of Access-Control-Request-Headers are explained here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Request-Headers

**Comment by lbroudoux** [comment]
Do you have a small HTML+JS page that would allow testing the different combination? In the case of https://github.com/microcks/microcks-quarkus/issues/22#issuecomment-1941485212 it seems that `content-type` is actually part of the request headers but not detected present into `Access-Control-Allow-Headers` in the preflight response.

**Comment by Apoorva64** [comment]
where should i execute thoses commands>? in webapp ?

**Comment by lbroudoux** [comment]
> @lbroudoux where should i execute thoses commands>? in webapp ?

Sorry 😉  No, from `distro/uber` folder.

**Comment by Apoorva64** [comment]
image
Works !

**Review by lbroudoux — APPROVED** [review]
LGTM and you've got a working test case on Quarkus Super Heroes! Woot!

**Pull request merged**
