### PR TITLE
feat: kafka login callback handler support

### PR DESCRIPTION
**Pull request by Afanas10101111**
### Description

- Add kafka sasl.login.callback.handler.class property support
- Add Dockerfile for quarkus legacy-jar build

### Related issue(s)

- <a href="https://github.com/microcks/microcks/issues/966">#966</a>

### CODE REVIEW

**Comment by lbroudoux** [comment]
Thanks for the PR! I am having a few days off at the moment but will probably have a look at it on Thursday. Cheers,

**Comment by lbroudoux** [comment]
Hi @Afanas10101111 

Is the `legacy-jar` packaging type required to load your customized callback handler implementation class? Am I correct? Is it the only way of doing this stuff for Quarkus app? I know there are different types of packaging and a re-augmentation process available, but I am not fully aware of the differences and pros vs cons.... Are there any helpful resources to better understand this?

We have the same concern that is enabling the loading of custom classes for the main component/container (see https://github.com/microcks/microcks/issues/897) and are in the process of describing the complete way of doing things. Could you elaborate on how you'll also project to use this for the minion component? That way we may try to make things consistent for both components.

Thanks,

**Comment by Afanas10101111** [comment]
Yes, You are correct! The standard package type for Quarkus apps is fast-jar and it indexes the contents of all dependencies at build time to provide a quick start. But I want to avoid rebuild each time I change handler implementation. To do this I need an app to use standard classloader, which in Quarkus apps available for legacy-jar package type (https://quarkus.io/guides/maven-tooling#fast-jar).

To use my custom handler class after building as legacy-jar I do next steps:

- add property kafka.sasl.login-callback-handler-class=my.custom.kafka.oauth.OAuthCallbackHandler

- add env property JAVA_CLASSPATH=/deployments/*:/deployments/custom/* (to use logic of /deployments/run-java.sh)

- mount my custom library to /deployments/custom/

- restart minion

- look at our messages in kafka :)

**Comment by Afanas10101111** [comment]
I have added the path to the app dir in `Dockerfile.legacy-jar`. Now instead of adding `JAVA_CLASSPATH` env with the path to the app dir and the custom lib dir, we need to add only `JAVA_LIB_DIR=/path/to/custom/lib/*`. And now without adding `kafka.sasl.login.callback.handler.class` and `JAVA_LIB_DIR` the minion runs as it was. I think this is a more clear way to configure this feature.

**Comment by lbroudoux** [comment]
Hey @Afanas10101111,
I got it working and checked that I can now load custom classes using the abovementioned mechanism! That's great!
However, I think it still needs extra configuration to get it fully working to support OAuth bearer. I'd like to be able to have a fully working example and grasp what other configuration variables (`kafka.sasl.login.callback.handler.class` but maybe also others...) we'd need to add as configuration properties in Microcks Helm Chart or Operator. Would you have a guide or procedure on how to test that with a Keycloak for example?

Thanks,

**Comment by Afanas10101111** [comment]
I assume that all extra configuration should be on the custom classes side. The idea is that when you use Kafka with oauth, you provide a client library, and its implementation may be different.

For example, <a href="https://github.com/strimzi/strimzi-kafka-oauth/blob/main/oauth-client/src/main/java/io/strimzi/kafka/oauth/client/JaasClientOauthLoginCallbackHandler.java">here is one of the possible implementations</a>. To use it we, need
- add in the minion `application.properties`
```
# Already existing fields
kafka.security.protocol=SASL_SSL
kafka.ssl.truststore.location=/deployments/config/truststore.jks
kafka.ssl.truststore.password=truststore_secret
kafka.sasl.mechanism=OAUTHBEARER
kafka.sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;

# New field
kafka.sasl.login-callback-handler-class=io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
```
- set env `JAVA_LIB_DIR=/path/to/strimzi/kafka-oauth-client/*:/path/to/strimzi/kafka-oauth-client/lib/*`
- mount directories with kafka-oauth-client.jar and its libs
- configure this handler according to <a href="https://github.com/strimzi/strimzi-kafka-oauth/tree/main#client-config-example">its documentation</a> by setting env `OAUTH_CLIENT_ID`, `OAUTH_CLIENT_SECRET` and `OAUTH_TOKEN_ENDPOINT_URI`

This last step may be completely different for different implementations. For example, the names of the parameters and their number may differ, or we may need to specify them in the properties file.

I hope this will help to understand my way of researching this feature and get a working sample :)

**Comment by lbroudoux** [comment]
Thanks!

> This last step may be completely different for different implementations. For example, the names of the parameters and their number may differ, or we may need to specify them in the properties file.

This point was the thing I wanted to check. We need adding - thus - the ability to add arbitrary environment variables and properties to the async-minion configuration.

In the case of properties in the `application.properties` file, I imagine we had to also store them into the Kafka producer properties so that they can be retrieved and used at configuration time by the `AuthenticationCallbackHandler` in `public void configure(Map<String, ?> map, String saslMechanism, List<AppConfigurationEntry> jaasConfigEntries)`? Could you confirm this later point?

**Comment by Afanas10101111** [comment]
I tested this feature with an implementation that depends on 'kafka-oauth.properties', and it was enough to add this file to the classpath (in the custom lib directory).
If the implementation directly depends on `application.properties`, it is enough to add the necessary properties to `application.properties` of the minion, I guess. I'll try to test such case tomorrow. But in this case, we have a risk of collision of property names, I'm afraid.

**Comment by Afanas10101111** [comment]
I've checked - with the implementation depends on `application.properties` everything works as I expected.

About this question
> In the case of properties in the application.properties file, I imagine we had to also store them into the Kafka producer properties so that they can be retrieved and used at configuration time by the AuthenticationCallbackHandler in public void configure(Map<String, ?> map, String saslMechanism, List<AppConfigurationEntry> jaasConfigEntries)? Could you confirm this later point?

Not quite. You are right, this method works with the Kafka producer properties. But our additional custom handler configuration is required to connect to the oauth server and get a token and should be configurated separately (by a propertiy file or/and env variables)

**Comment by lbroudoux** [comment]
Thanks again for this contribution!

**Comment by lbroudoux** [comment]
@Afanas10101111 
I'm sorry, man, but I screwed this one and merged it into `master`... I had to revert this as the devs are going into branch `1.8.x` at the moment. Could you re-create your PR targeting this branch? I'd merge it super quickly now.
Sorry again.

**Pull request merged**
